spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:://127.0.0.1:3306/ohmycat
    username: root
    password: asdf
  thymeleaf:
    prefix: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

server:
  port: 8082
